create extension if not exists pgcrypto;

create table lists (id uuid primary key default gen_random_uuid(), user_id text not null, name text not null, created_at timestamptz not null default now(), unique(user_id, name));
create table goals (id uuid primary key default gen_random_uuid(), user_id text not null, title text not null, level text not null check(level in ('life','yearly','monthly','weekly','daily','exam')), parent_goal_id uuid references goals(id), depends_on_goal_id uuid references goals(id), target_date date, status text not null default 'proposed' check(status in ('proposed','active','completed','abandoned')), created_at timestamptz not null default now());
create table tasks (id uuid primary key default gen_random_uuid(), user_id text not null, list_id uuid references lists(id), goal_id uuid references goals(id), title text not null, description text, due_at timestamptz, priority text not null default 'normal' check(priority in ('low','normal','high','urgent')), status text not null default 'todo' check(status in ('todo','doing','done')), source text not null default 'manual' check(source in ('manual','goal_cascade','urgent','exam_plan')), completed_at timestamptz, created_at timestamptz not null default now());
create table reminders (id uuid primary key default gen_random_uuid(), task_id uuid not null references tasks(id) on delete cascade, remind_at timestamptz not null, kind text not null, status text not null default 'pending' check(status in ('pending','sending','sent','cancelled','failed')), lease_until timestamptz, failed_reason text, created_at timestamptz not null default now());
create table reviews (id uuid primary key default gen_random_uuid(), user_id text not null, type text not null check(type in ('daily','weekly','monthly')), period_start date not null, period_end date not null, summary text, raw_reply text, created_at timestamptz not null default now());
create table inbound_messages (id uuid primary key default gen_random_uuid(), user_id text not null, message_sid text not null unique, from_number text not null, body text not null, received_at timestamptz not null default now());
create table inbound_queue (id uuid primary key default gen_random_uuid(), inbound_id uuid not null unique references inbound_messages(id) on delete cascade, user_id text not null, status text not null default 'pending' check(status in ('pending','processing','done')), lease_owner text, lease_until timestamptz, attempts integer not null default 0, created_at timestamptz not null default now());
create table outbox (id uuid primary key default gen_random_uuid(), user_id text not null, to_number text not null, body text not null, kind text not null default 'reply', reminder_id uuid references reminders(id), status text not null default 'pending' check(status in ('pending','sending','sent','failed')), attempts integer not null default 0, next_attempt_at timestamptz not null default now(), lease_owner text, lease_until timestamptz, failed_reason text, created_at timestamptz not null default now());
create table task_list_snapshots (id uuid primary key default gen_random_uuid(), user_id text not null, task_ids uuid[] not null, shown_at timestamptz, expires_at timestamptz not null, created_at timestamptz not null default now());
create table conversation_state (user_id text primary key, kind text not null, payload jsonb not null default '{}'::jsonb, expires_at timestamptz not null, updated_at timestamptz not null default now());
create index reminders_due_idx on reminders(status, remind_at); create index queue_claim_idx on inbound_queue(user_id, status, created_at); create index outbox_due_idx on outbox(status, next_attempt_at);

create or replace function enqueue_inbound_message(p_inbound_id uuid) returns void language plpgsql security definer as $$
declare v_user text; begin select user_id into v_user from inbound_messages where id=p_inbound_id; insert into inbound_queue(inbound_id,user_id) values(p_inbound_id,v_user) on conflict(inbound_id) do nothing; end $$;

create or replace function claim_inbound_messages(p_worker_id text, p_lease_seconds int) returns table(id uuid,user_id text,message_sid text,body text,from_number text,received_at timestamptz,attempts int,metadata jsonb) language sql security definer as $$
 with candidate as (select q.id from inbound_queue q where (q.status='pending' or (q.status='processing' and q.lease_until < now())) and not exists (select 1 from inbound_queue older where older.user_id=q.user_id and older.created_at<q.created_at and older.status in ('pending','processing') and (older.lease_until is null or older.lease_until >= now())) order by q.created_at for update skip locked limit 10), claimed as (update inbound_queue q set status='processing',lease_owner=p_worker_id,lease_until=now()+make_interval(secs=>p_lease_seconds),attempts=q.attempts+1 from candidate c where q.id=c.id returning q.*) select c.id,c.user_id,m.message_sid,m.body,m.from_number,m.received_at,c.attempts,'{}'::jsonb from claimed c join inbound_messages m on m.id=c.inbound_id; $$;
create or replace function finish_inbound_message(p_queue_id uuid,p_worker_id text) returns void language sql security definer as $$ update inbound_queue set status='done',lease_owner=null,lease_until=null where id=p_queue_id and lease_owner=p_worker_id; $$;
create or replace function release_inbound_message(p_queue_id uuid,p_worker_id text) returns void language sql security definer as $$ update inbound_queue set status='pending',lease_owner=null,lease_until=null where id=p_queue_id and lease_owner=p_worker_id; $$;

create or replace function set_conversation_state(p_user_id text,p_kind text,p_payload jsonb) returns void language sql security definer as $$ insert into conversation_state(user_id,kind,payload,expires_at) values(p_user_id,p_kind,p_payload,now()+interval '24 hours') on conflict(user_id) do update set kind=excluded.kind,payload=excluded.payload,expires_at=excluded.expires_at,updated_at=now(); $$;
create or replace function expire_conversation_state() returns void language sql security definer as $$ delete from conversation_state where expires_at < now(); $$;
create or replace function activate_goal_proposal(p_user_id text) returns void language plpgsql security definer as $$ declare s conversation_state; declare g uuid; declare child jsonb; declare child_level text; begin select * into s from conversation_state where user_id=p_user_id and kind='goal_confirmation' and expires_at>now() for update; if not found then raise exception 'No active goal proposal'; end if; child_level := case s.payload->'goal'->>'goal_level' when 'life' then 'yearly' when 'yearly' then 'monthly' when 'monthly' then 'weekly' else 'daily' end; insert into goals(user_id,title,level,target_date,status) values(p_user_id,s.payload->'goal'->>'title',s.payload->'goal'->>'goal_level',nullif(s.payload->'goal'->>'target_date','')::date,'active') returning id into g; for child in select * from jsonb_array_elements(s.payload->'items'->'items') loop insert into goals(user_id,title,level,parent_goal_id,target_date,status) values(p_user_id,child->>'title',child_level,g,nullif(child->>'target_date','')::date,'active'); end loop; delete from conversation_state where user_id=p_user_id; end $$;

create or replace function create_task_with_reminders(p_user_id text,p_title text,p_description text,p_list_name text,p_due_at timestamptz,p_priority text,p_source text) returns setof tasks language plpgsql security definer as $$ declare v_list uuid; declare v_task tasks; begin insert into lists(user_id,name) values(p_user_id,p_list_name) on conflict(user_id,name) do update set name=excluded.name returning id into v_list; insert into tasks(user_id,list_id,title,description,due_at,priority,source) values(p_user_id,v_list,p_title,p_description,p_due_at,p_priority,p_source) returning * into v_task; if p_due_at is not null then insert into reminders(task_id,remind_at,kind) values(v_task.id, p_due_at-interval '24 hours','before_due'),(v_task.id,p_due_at,'due') on conflict do nothing; if p_source='urgent' then insert into reminders(task_id,remind_at,kind) values(v_task.id,greatest(now(),date_trunc('day',now())+interval '19 hours'),'urgent_evening'),(v_task.id,date_trunc('day',p_due_at)+interval '9 hours','urgent_morning'); end if; end if; return next v_task; end $$;
create or replace function prioritized_open_tasks(p_user_id text,p_view text) returns setof tasks language sql security definer as $$ select t.* from tasks t where t.user_id=p_user_id and t.status in ('todo','doing') and (p_view <> 'today' or t.due_at is null or t.due_at < date_trunc('day',now())+interval '1 day') order by case when t.due_at < now() then 0 when t.priority='urgent' and t.due_at < now()+interval '48 hours' then 1 when t.source='exam_plan' and t.due_at::date=now()::date then 2 when t.source='goal_cascade' then 3 else 4 end, case t.priority when 'urgent' then 0 when 'high' then 1 when 'normal' then 2 else 3 end, t.due_at nulls last; $$;
create or replace function complete_task(p_task_id uuid) returns void language sql security definer as $$ update tasks set status='done',completed_at=now() where id=p_task_id; update reminders set status='cancelled' where task_id=p_task_id and status in ('pending','sending'); $$;
create or replace function complete_snapshot_task(p_user_id text,p_number int) returns setof tasks language plpgsql security definer as $$ declare v_task uuid; begin select s.task_ids[p_number] into v_task from task_list_snapshots s where s.user_id=p_user_id and s.expires_at>now() order by s.shown_at desc nulls last limit 1; if v_task is null then return; end if; perform complete_task(v_task); return query select * from tasks where id=v_task; end $$;
create or replace function find_open_task(p_user_id text,p_query text) returns setof tasks language sql security definer as $$ select * from tasks where user_id=p_user_id and status in ('todo','doing') and title ilike '%'||p_query||'%' order by due_at nulls last limit 5; $$;
create or replace function reschedule_task_with_reminders(p_task_id uuid,p_due_at timestamptz) returns void language plpgsql security definer as $$ begin update tasks set due_at=p_due_at where id=p_task_id; update reminders set status='cancelled' where task_id=p_task_id and status in ('pending','sending'); insert into reminders(task_id,remind_at,kind) values(p_task_id,p_due_at-interval '24 hours','before_due'),(p_task_id,p_due_at,'due'); end $$;
create or replace function create_exam_plan(p_user_id text,p_subject text,p_exam_date date,p_sessions jsonb) returns void language plpgsql security definer as $$ declare g uuid; declare x jsonb; begin insert into goals(user_id,title,level,target_date,status) values(p_user_id,p_subject||' exam','exam',p_exam_date,'active') returning id into g; for x in select * from jsonb_array_elements(p_sessions) loop perform create_task_with_reminders(p_user_id,x->>'title',null,'Academics',(x->>'due_at')::timestamptz,coalesce(x->>'priority','high'),'exam_plan'); update tasks set goal_id=g where id=(select id from tasks where user_id=p_user_id order by created_at desc limit 1); end loop; end $$;
create or replace function record_review_reply(p_user_id text,p_raw_reply text) returns void language sql security definer as $$ update reviews set raw_reply=p_raw_reply where id=(select id from reviews where user_id=p_user_id and raw_reply is null order by created_at desc limit 1); $$;

create or replace function claim_outbox(p_worker_id text,p_max_attempts int) returns setof outbox language sql security definer as $$ with c as (select id from outbox where (status='pending' and next_attempt_at<=now()) or (status='sending' and lease_until<now()) order by created_at for update skip locked limit 30), u as (update outbox o set status='sending',lease_owner=p_worker_id,lease_until=now()+interval '2 minutes' from c where o.id=c.id returning o.*) select * from u; $$;
create or replace function complete_outbox(p_outbox_id uuid,p_worker_id text) returns void language sql security definer as $$ update outbox set status='sent',lease_owner=null,lease_until=null where id=p_outbox_id and lease_owner=p_worker_id; $$;
create or replace function fail_outbox(p_outbox_id uuid,p_worker_id text,p_error text,p_max_attempts int) returns void language plpgsql security definer as $$
declare v_reminder_id uuid;
declare v_status text;
begin
  update outbox
  set attempts=attempts+1,
      status=case when attempts+1>=p_max_attempts then 'failed' else 'pending' end,
      next_attempt_at=now()+make_interval(secs=>least(3600,60*power(2,attempts)::int)),
      lease_owner=null,
      lease_until=null,
      failed_reason=p_error
  where id=p_outbox_id and lease_owner=p_worker_id
  returning reminder_id, status into v_reminder_id, v_status;

  if v_status='failed' and v_reminder_id is not null then
    update reminders set status='failed', failed_reason=p_error where id=v_reminder_id;
  end if;
end $$;
create or replace function queue_due_reminders(p_worker_id text) returns void language plpgsql security definer as $$ begin insert into outbox(user_id,to_number,body,kind,reminder_id) select t.user_id,t.user_id,'Reminder: '||t.title,'reminder',r.id from reminders r join tasks t on t.id=r.task_id where r.status='pending' and r.remind_at<=now() and t.status in ('todo','doing'); update reminders r set status='sent' from tasks t where t.id=r.task_id and r.status='pending' and r.remind_at<=now() and t.status in ('todo','doing'); end $$;
create or replace function queue_due_reviews(p_timezone text) returns void language plpgsql security definer as $$ declare u text; declare failures int; begin for u in select distinct user_id from tasks loop if not exists(select 1 from reviews where user_id=u and type='daily' and period_start=current_date) then select count(*) into failures from outbox where user_id=u and kind='reminder' and status='failed' and created_at>=date_trunc('day',now()); insert into reviews(user_id,type,period_start,period_end) values(u,'daily',current_date,current_date); insert into outbox(user_id,to_number,body,kind) values(u,u,'Daily review: reply with what you finished and any blockers.' || case when failures>0 then ' Note: '||failures||' reminder(s) could not be delivered.' else '' end,'review'); end if; end loop; end $$;
